# Site settings
title: 鲁大学生网 团队博客
email: ludongstudent@foxmail.com
description: 这里是鲁大学生网团队的博客（Our team blog）!!!   欢迎各位光临~~~<br/>鲁大学生网以“二”为文化，以“家”为特色，以“开放、自由、创新”为旗帜，以“实现自我，服务鲁大”为宗旨，为描绘鲁大青春，走当代大学生前列而努力奋斗。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ldsn.github.io/sailboat/" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
